replicaCount: 1

image:
  repository: docker.io/annt17/flask-app
  tag: 1.0-25.0518.0210_main_16ff20b
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  nodePort: 30052

env:
  WELCOME_MSG: "Hello from upgraded Helm!"
  DB_PASSWORD: "secret_password"
